name: Deploy Next.js Blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: Production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.4'

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js App
        run: npm run build

      - name: Install PM2
        run: npm install pm2 -g

      - name: Start/Restart Next.js App with PM2
        run: |
          cd /home/makizo/blog
          git pull origin main
          npm ci
          npm run build
          pm2 delete blog || true
          pm2 start npm --name "blog" -- start -- -p ${{ vars.PORT }}
